"""full_schema_baseline

Revision ID: 05c4047cd0e7
Revises: 0001
Create Date: 2026-04-02 18:25:37.995722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05c4047cd0e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False, comment='对应 resource_type'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pt_type_active', 'prompt_templates', ['resource_type', 'is_active'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述（Markdown）'),
    sa.Column('task_type', sa.String(length=30), nullable=False, comment='类型: homework|review|practice|exploration'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft|published|archived'),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=False, comment='创建者 user_id'),
    sa.Column('subject', sa.String(length=30), nullable=True, comment='学科'),
    sa.Column('grade_range', sa.String(length=30), nullable=True, comment='年级范围 grade_{start}-grade_{end}'),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True, comment='定时发布时间'),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True, comment='截止时间'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='任务配置: max_attempts, time_limit_minutes, pass_score 等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_created_by', 'tasks', ['created_by'], unique=False)
    op.create_index('idx_tasks_publish', 'tasks', ['publish_at'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('textbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=30), nullable=False, comment='math/chinese/english/physics/chemistry/biology/history/geography/politics'),
    sa.Column('grade_range', sa.String(length=30), nullable=False, comment='grade_7-grade_9'),
    sa.Column('source_file_url', sa.String(length=500), nullable=False, comment='MinIO 原始文件地址'),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False, comment='pending/parsing/completed/failed'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外元信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_textbooks_grade', 'textbooks', ['grade_range'], unique=False)
    op.create_index('idx_textbooks_status', 'textbooks', ['parse_status'], unique=False)
    op.create_index('idx_textbooks_subject', 'textbooks', ['subject'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像 URL'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: student|admin|guardian|teacher'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_phone_active', 'users', ['phone'], unique=True, postgresql_where='phone IS NOT NULL AND deleted_at IS NULL')
    op.create_table('chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('textbook_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='父章节，NULL 表示顶层'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True, comment='该章节提取的文本内容'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chapters_parent', 'chapters', ['parent_id'], unique=False)
    op.create_index('idx_chapters_textbook', 'chapters', ['textbook_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False, comment='学生 user_id'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题（自动生成或用户修改）'),
    sa.Column('scene', sa.String(length=30), nullable=False, comment='场景: free_chat|homework_help|concept_explain|review_guide|error_analysis'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: active|archived'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='冗余消息计数'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='最后一条消息时间'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='会话上下文: task_id, chapter_id, knowledge_point_ids, difficulty, student_grade, system_prompt_override'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_scene', 'conversations', ['scene'], unique=False)
    op.create_index('idx_conv_student', 'conversations', ['student_id', 'updated_at'], unique=False)
    op.create_table('guardian_bindings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('guardian_id', sa.UUID(as_uuid=False), nullable=False, comment='家长 user_id'),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False, comment='学生 user_id'),
    sa.Column('relationship_type', sa.String(length=20), nullable=False, comment='关系类型: parent|grandparent|other'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否为主要监护人'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gb_guardian_student', 'guardian_bindings', ['guardian_id', 'student_id'], unique=True)
    op.create_table('learning_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False, comment='学生 user_id'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='任务标题'),
    sa.Column('task_type', sa.String(length=30), nullable=False, comment='类型: exercise|reading|review'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: pending|in_progress|completed|expired'),
    sa.Column('subject', sa.String(length=30), nullable=True, comment='学科'),
    sa.Column('knowledge_point_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='关联知识点 ID 列表'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='任务配置'),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True, comment='截止时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lt_status', 'learning_tasks', ['status'], unique=False)
    op.create_index('idx_lt_student', 'learning_tasks', ['student_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='年级: grade_1 ~ grade_12'),
    sa.Column('school_name', sa.String(length=100), nullable=True, comment='学校名称'),
    sa.Column('learning_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='学习风格偏好'),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='兴趣标签'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_sp_grade', 'student_profiles', ['grade'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False, comment='学生 user_id'),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=True, comment='关联任务 ID'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='学习时长（秒）'),
    sa.Column('activity_type', sa.String(length=30), nullable=False, comment='活动类型: study|quiz|review|ai_chat'),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='会话摘要数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ss_student', 'study_sessions', ['student_id'], unique=False)
    op.create_index('idx_ss_task', 'study_sessions', ['task_id'], unique=False)
    op.create_table('task_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False, comment='类型: game|video_script|quiz|reading|ai_chat'),
    sa.Column('resource_id', sa.UUID(as_uuid=False), nullable=True, comment='关联 content.generated_resources.id'),
    sa.Column('knowledge_point_id', sa.UUID(as_uuid=False), nullable=True, comment='关联知识点'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='子项标题'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='子项配置'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_items_task', 'task_items', ['task_id', 'sort_order'], unique=False)
    op.create_table('task_progress',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False, comment='学生 user_id'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: not_started|in_progress|completed'),
    sa.Column('score', sa.Integer(), nullable=True, comment='得分（0-100）'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('item_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='各子项完成情况: { item_id: { status, score, attempts } }'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tp_status', 'task_progress', ['status'], unique=False)
    op.create_index('idx_tp_student_task', 'task_progress', ['student_id', 'task_id'], unique=True)
    op.create_table('user_oauth_bindings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False, comment='wechat|feishu|google'),
    sa.Column('provider_user_id', sa.String(length=200), nullable=False, comment='第三方平台用户 ID'),
    sa.Column('access_token', sa.String(length=500), nullable=True, comment='访问令牌'),
    sa.Column('refresh_token', sa.String(length=500), nullable=True, comment='刷新令牌'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='令牌过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uob_provider', 'user_oauth_bindings', ['provider', 'provider_user_id'], unique=True)
    op.create_table('knowledge_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False, comment='1-5'),
    sa.Column('bloom_level', sa.String(length=30), nullable=True, comment='remember/understand/apply/analyze/evaluate/create'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kp_chapter', 'knowledge_points', ['chapter_id'], unique=False)
    op.create_index('idx_kp_difficulty', 'knowledge_points', ['difficulty'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色: user|assistant|system'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息正文（Markdown）'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='本条消息 token 数'),
    sa.Column('model_name', sa.String(length=50), nullable=True, comment='使用的 LLM 模型'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展元数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_conv', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('generated_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_point_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False, comment='quiz/game/video_script/summary/exercise'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='资源内容 JSON'),
    sa.Column('prompt_template_id', sa.UUID(), nullable=True, comment='生成时使用的 prompt 模板'),
    sa.Column('llm_model', sa.String(length=50), nullable=True, comment='生成使用的 LLM 模型'),
    sa.Column('quality_score', sa.Integer(), nullable=True, comment='质量评分 1-5'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gr_kp', 'generated_resources', ['knowledge_point_id'], unique=False)
    op.create_index('idx_gr_type', 'generated_resources', ['resource_type'], unique=False)
    op.create_table('kp_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('knowledge_point_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='embedding 模型名'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False, comment='向量'),
    sa.Column('source_text', sa.Text(), nullable=True, comment='用于生成向量的原文'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kpe_kp', 'kp_embeddings', ['knowledge_point_id'], unique=False)
    op.create_table('mastery_records',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('student_id', sa.UUID(as_uuid=False), nullable=False, comment='学生 user_id'),
    sa.Column('knowledge_point_id', sa.UUID(as_uuid=False), nullable=False, comment='知识点 ID'),
    sa.Column('mastery_level', sa.Float(), nullable=False, comment='掌握度 0.0-1.0'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='练习次数'),
    sa.Column('correct_count', sa.Integer(), nullable=False, comment='正确次数'),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True, comment='上次练习时间'),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='历史记录'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mr_student_kp', 'mastery_records', ['student_id', 'knowledge_point_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mr_student_kp', table_name='mastery_records')
    op.drop_table('mastery_records')
    op.drop_index('idx_kpe_kp', table_name='kp_embeddings')
    op.drop_table('kp_embeddings')
    op.drop_index('idx_gr_type', table_name='generated_resources')
    op.drop_index('idx_gr_kp', table_name='generated_resources')
    op.drop_table('generated_resources')
    op.drop_index('idx_msg_conv', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_kp_difficulty', table_name='knowledge_points')
    op.drop_index('idx_kp_chapter', table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_index('idx_uob_provider', table_name='user_oauth_bindings')
    op.drop_table('user_oauth_bindings')
    op.drop_index('idx_tp_student_task', table_name='task_progress')
    op.drop_index('idx_tp_status', table_name='task_progress')
    op.drop_table('task_progress')
    op.drop_index('idx_task_items_task', table_name='task_items')
    op.drop_table('task_items')
    op.drop_index('idx_ss_task', table_name='study_sessions')
    op.drop_index('idx_ss_student', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index('idx_sp_grade', table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index('idx_lt_student', table_name='learning_tasks')
    op.drop_index('idx_lt_status', table_name='learning_tasks')
    op.drop_table('learning_tasks')
    op.drop_index('idx_gb_guardian_student', table_name='guardian_bindings')
    op.drop_table('guardian_bindings')
    op.drop_index('idx_conv_student', table_name='conversations')
    op.drop_index('idx_conv_scene', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_chapters_textbook', table_name='chapters')
    op.drop_index('idx_chapters_parent', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index('ix_users_phone_active', table_name='users', postgresql_where='phone IS NOT NULL AND deleted_at IS NULL')
    op.drop_table('users')
    op.drop_index('idx_textbooks_subject', table_name='textbooks')
    op.drop_index('idx_textbooks_status', table_name='textbooks')
    op.drop_index('idx_textbooks_grade', table_name='textbooks')
    op.drop_table('textbooks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_publish', table_name='tasks')
    op.drop_index('idx_tasks_created_by', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_pt_type_active', table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
